### ISSUE TITLE
Add option to hide notifications icon popup box

### ISSUE THREAD

**Issue by ghost** [gnome-integration-team/firefox-gnome-tweak#5]
```
@-moz-document url(chrome://browser/content/browser.xul) {

    #urlbar #notification-popup-box {
        display: none !important;
    }

}
```

**Comment by seleznev** [comment]
Hm... I don't think that it's good idea. AFAIR, we had problems with review when we had no green background for the #identity-box.

https://wiki.mozilla.org/AMO:Editors/EditorGuide/ThemeReviews#Identity_Boxes

(We have extension in the theme package now. I don't know how reviewers will appreciate this tweak. However, I don't see any another problems)

**Comment by ghost** [comment]
I can understand this, so changed the subject to affect only notification popup.
Also I don't think there is significant need for such option and it can raise more problems, so I close issue :)
