### ISSUE TITLE
Firefox 39.0

### ISSUE THREAD

**Issue by algarni** [gnome-integration-team/firefox-gnome-tweak#7]
Hi,

This add-on is not available for Firefox 39.0. Is there any plan to fix this?

**Comment by seleznev** [comment]
No, the latest version support Fx 40+ and it's correct. May be you should install one of old version from https://addons.mozilla.org/ru/firefox/addon/gnome-theme-tweak/versions/ page.

ps. This extension was moved into [gnome-theme](https://github.com/gnome-integration-team/firefox-gnome) repository.
